const { getPool } = require('../db');
const resolver = require('./apk-resolver');
const activity = require('./activity');
const notifications = require('./notifications');
const SCAN_KEY='apk-managed';
async function state(){const [rows]=await getPool().query('SELECT * FROM apk_update_state WHERE scan_key=? LIMIT 1',[SCAN_KEY]);return rows[0]||{scan_key:SCAN_KEY,status:'idle',queue_json:'[]',total_count:0,processed_count:0,update_count:0,failed_count:0,requested_by:null,completion_notified:0}}
async function start(requestedBy=null,limit=20){const db=getPool();const cap=Math.max(1,Math.min(50000,Number(limit)||20));const [rows]=await db.query('SELECT id FROM apps ORDER BY id');const queue=rows.slice(0,cap).map(r=>Number(r.id));await db.query(`INSERT INTO apk_update_state (scan_key,requested_by,completion_notified,status,queue_json,total_count,processed_count,update_count,failed_count,current_app_id,last_error) VALUES (?,?,0,'running',?,?,0,0,0,NULL,NULL) ON DUPLICATE KEY UPDATE requested_by=VALUES(requested_by),completion_notified=0,status='running',queue_json=VALUES(queue_json),total_count=VALUES(total_count),processed_count=0,update_count=0,failed_count=0,current_app_id=NULL,last_error=NULL`,[SCAN_KEY,requestedBy?Number(requestedBy):null,JSON.stringify(queue),queue.length]);if(requestedBy)await activity.record(Number(requestedBy),'apk_update_scan_started',{details:{total:queue.length}});return state()}
async function stop(){const db=getPool();await db.query("UPDATE apk_update_state SET status='stopped',queue_json='[]',current_app_id=NULL WHERE scan_key=?",[SCAN_KEY]);return state()}
async function notifyCompleted(st){if(!st||st.status!=='complete'||!Number(st.requested_by||0)||Number(st.completion_notified||0))return st;const db=getPool();const [mark]=await db.query('UPDATE apk_update_state SET completion_notified=1 WHERE scan_key=? AND completion_notified=0',[SCAN_KEY]);if(!mark.affectedRows)return state();const uid=Number(st.requested_by),found=Number(st.update_count||0),failed=Number(st.failed_count||0),checked=Number(st.processed_count||0);await activity.record(uid,'apk_update_scan_completed',{details:{checked,updates:found,failed}});await notifications.notifyUser(uid,{actorUserId:uid,type:failed?'warning':found?'info':'success',title:'APK update scan completed',message:`${checked.toLocaleString()} checked · ${found.toLocaleString()} update(s) found · ${failed.toLocaleString()} failed.`,dedupeKey:`apk-update-scan-${new Date(st.updated_at||Date.now()).getTime()}`});return state()}
async function step(){const db=getPool();let st=await state();if(st.status==='idle')st=await start(st.requested_by||null);if(st.status!=='running')return notifyCompleted(st);let queue=[];try{queue=JSON.parse(st.queue_json||'[]')}catch{}if(!queue.length){await db.query("UPDATE apk_update_state SET status='complete',current_app_id=NULL WHERE scan_key=?",[SCAN_KEY]);return notifyCompleted(await state())}const id=queue.shift();await db.query('UPDATE apk_update_state SET current_app_id=?,queue_json=? WHERE scan_key=?',[id,JSON.stringify(queue),SCAN_KEY]);try{const [[app]]=await db.query('SELECT * FROM apps WHERE id=? LIMIT 1',[id]);if(app){const checked=await resolver.checkUpdateForApp(app);await db.query('UPDATE apk_update_state SET processed_count=processed_count+1,update_count=update_count+? WHERE scan_key=?',[checked.available?1:0,SCAN_KEY])}else await db.query('UPDATE apk_update_state SET processed_count=processed_count+1 WHERE scan_key=?',[SCAN_KEY])}catch(err){await db.query('UPDATE apps SET last_checked_at=NOW(),update_error=? WHERE id=?',[String(err.message||err).slice(0,1800),id]);await db.query('UPDATE apk_update_state SET processed_count=processed_count+1,failed_count=failed_count+1,last_error=? WHERE scan_key=?',[String(err.message||err).slice(0,1800),SCAN_KEY])}if(!queue.length)await db.query("UPDATE apk_update_state SET status='complete',current_app_id=NULL WHERE scan_key=?",[SCAN_KEY]);return notifyCompleted(await state())}
module.exports={state,start,stop,step,markUpdated:resolver.markUpdated};
