const crypto=require('crypto');const{getPool}=require('../db');const activity=require('./activity');
const LOCK_TIMEOUT_SECONDS=Math.max(60,Math.min(300,Number(process.env.WORK_LOCK_TIMEOUT_SECONDS||90)||90));
function claimJson(row){if(!row)return null;return{appId:Number(row.app_id),userId:Number(row.user_id),name:row.user_name||row.name||'User',role:row.user_role||row.role||'partner',roleLabel:String(row.user_role||row.role||'').toLowerCase()==='admin'?'Admin':'Partner',claimedAt:row.claimed_at||null,lastHeartbeatAt:row.last_heartbeat_at||null}}
async function pruneStaleClaims(db=getPool(),appId=null){const sql=appId==null?`DELETE FROM app_work_claims WHERE last_heartbeat_at < DATE_SUB(NOW(), INTERVAL ${LOCK_TIMEOUT_SECONDS} SECOND)`:`DELETE FROM app_work_claims WHERE app_id=? AND last_heartbeat_at < DATE_SUB(NOW(), INTERVAL ${LOCK_TIMEOUT_SECONDS} SECOND)`;const [r]=await db.query(sql,appId==null?[]:[Number(appId)]);return Number(r.affectedRows||0)}
async function getClaim(appId,db=getPool()){await pruneStaleClaims(db,appId);const [[row]]=await db.query('SELECT c.app_id,c.user_id,c.claimed_at,c.last_heartbeat_at,u.name user_name,u.role user_role FROM app_work_claims c JOIN users u ON u.id=c.user_id WHERE c.app_id=? LIMIT 1',[Number(appId)]);return claimJson(row)}
async function listActiveClaims(){const db=getPool();await pruneStaleClaims(db);const [rows]=await db.query('SELECT c.app_id,c.user_id,c.claimed_at,c.last_heartbeat_at,u.name user_name,u.role user_role FROM app_work_claims c JOIN users u ON u.id=c.user_id ORDER BY c.app_id');return rows.map(claimJson)}
async function appExists(id,db=getPool()){const [[r]]=await db.query('SELECT id FROM apps WHERE id=? LIMIT 1',[Number(id)]);return Boolean(r)}
async function claimApp(id,user){const db=getPool();id=Number(id);if(!id||!(await appExists(id,db)))throw Object.assign(new Error('App not found.'),{status:404});const before=await getClaim(id,db);if(before?.userId===Number(user.id)){await db.query('UPDATE app_work_claims SET last_heartbeat_at=NOW() WHERE app_id=? AND user_id=?',[id,Number(user.id)]);return{ok:true,owned:true,claim:await getClaim(id,db)}}if(before)return{ok:false,owned:false,claim:before};const token=crypto.randomBytes(24).toString('hex');await db.query(`INSERT INTO app_work_claims (app_id,user_id,lock_token,claimed_at,last_heartbeat_at) VALUES (?,?,?,NOW(),NOW()) ON DUPLICATE KEY UPDATE app_id=VALUES(app_id)`,[id,Number(user.id),token]);const claim=await getClaim(id,db);if(claim?.userId===Number(user.id)){await activity.record(user.id,'app_claimed',{appId:id});return{ok:true,owned:true,claim}}return{ok:false,owned:false,claim}}
async function heartbeat(id,userId){const db=getPool();const [r]=await db.query(`UPDATE app_work_claims SET last_heartbeat_at=NOW() WHERE app_id=? AND user_id=? AND last_heartbeat_at >= DATE_SUB(NOW(), INTERVAL ${LOCK_TIMEOUT_SECONDS} SECOND)`,[Number(id),Number(userId)]);if(!r.affectedRows){await pruneStaleClaims(db,id);return{ok:false,claim:await getClaim(id,db)}}return{ok:true,claim:await getClaim(id,db)}}
async function release(id,user,{force=false}={}){const db=getPool(),claim=await getClaim(id,db);if(!claim)return{released:false,claim:null};const own=claim.userId===Number(user.id);if(!own&&!(force&&user.role==='admin'))throw Object.assign(new Error(`${claim.name} is currently working on this app.`),{status:423,claim});await db.query('DELETE FROM app_work_claims WHERE app_id=?',[Number(id)]);await activity.record(user.id,own?'app_released':'app_force_released',{appId:id,targetUserId:own?null:claim.userId});return{released:true,claim:null}}
async function takeover(id,user){if(user.role!=='admin')throw Object.assign(new Error('Only the Admin can take over another user’s app.'),{status:403});const db=getPool();if(!(await appExists(id,db)))throw Object.assign(new Error('App not found.'),{status:404});const previous=await getClaim(id,db),token=crypto.randomBytes(24).toString('hex');await db.query(`INSERT INTO app_work_claims (app_id,user_id,lock_token,claimed_at,last_heartbeat_at) VALUES (?,?,?,NOW(),NOW()) ON DUPLICATE KEY UPDATE user_id=VALUES(user_id),lock_token=VALUES(lock_token),claimed_at=NOW(),last_heartbeat_at=NOW()`,[Number(id),Number(user.id),token]);await activity.record(user.id,'app_taken_over',{appId:id,targetUserId:previous?.userId||null});return{ok:true,claim:await getClaim(id,db),previous}}
async function ensureNotOwnedByOther(id,user){const claim=await getClaim(id);if(claim&&claim.userId!==Number(user.id))throw Object.assign(new Error(`${claim.name} is currently working on this app.`),{status:423,claim});return claim}
async function releaseOwned(id,userId){await getPool().query('DELETE FROM app_work_claims WHERE app_id=? AND user_id=?',[Number(id),Number(userId)])}
async function releaseAllOwned(userId){const [r]=await getPool().query('DELETE FROM app_work_claims WHERE user_id=?',[Number(userId)]);return Number(r.affectedRows||0)}
module.exports={LOCK_TIMEOUT_SECONDS,claimJson,pruneStaleClaims,getClaim,listActiveClaims,claimApp,heartbeat,release,takeover,ensureNotOwnedByOther,releaseOwned,releaseAllOwned};
