const fs=require('fs');const path=require('path');const state=require('../state');const{getPool}=require('../db');const activity=require('./activity');const notifications=require('./notifications');
const BACKUP_DIR=path.join(process.cwd(),'backups');const AUTO_INTERVAL_MS=24*60*60*1000;const CHECK_INTERVAL_MS=60*1000;const AUTO_RETENTION=30;const MANUAL_RETENTION=20;const BACKUP_FORMAT_VERSION=3;const APP_VERSION='1.2.2';let workerStarted=false,running=false,restoring=false;
function ensureDir(){fs.mkdirSync(BACKUP_DIR,{recursive:true})}function safeFilename(kind='manual'){return`appbit-${kind}-backup-${new Date().toISOString().replace(/[:.]/g,'-')}.json`}
async function rows(db,t){const[r]=await db.query(`SELECT * FROM \`${t}\``);return r}
async function createBackup(kind='manual'){if(running)throw new Error('A backup is already being created.');running=true;try{ensureDir();const db=getPool();const[[schema]]=await db.query('SELECT MAX(version) version FROM schema_migrations');const payload={backup_format:'appbit-json-backup',backup_version:BACKUP_FORMAT_VERSION,app_version:APP_VERSION,schema_version:Number(schema?.version||0),created_at:new Date().toISOString(),kind,data:{apps:await rows(db,'apps'),apk_versions:await rows(db,'apk_versions'),apk_media:await rows(db,'apk_media'),apk_metadata:await rows(db,'apk_metadata'),publish_queue:await rows(db,'publish_queue'),apk_categories:await rows(db,'apk_categories')}};const filename=safeFilename(kind),filepath=path.join(BACKUP_DIR,filename),json=JSON.stringify(payload,null,2);fs.writeFileSync(filepath,json,'utf8');const size=Buffer.byteLength(json);const[result]=await db.query('INSERT INTO backup_history (backup_kind,filename,file_size_bytes) VALUES (?,?,?)',[kind,filename,size]);await pruneBackups(kind);return{id:Number(result.insertId),kind,filename,fileSizeBytes:size,createdAt:payload.created_at}}finally{running=false}}
async function pruneBackups(kind){const db=getPool(),limit=kind==='auto'?AUTO_RETENTION:kind==='manual'?MANUAL_RETENTION:5;const[rs]=await db.query('SELECT id,filename FROM backup_history WHERE backup_kind=? ORDER BY created_at DESC,id DESC',[kind]);for(const r of rs.slice(limit)){try{fs.unlinkSync(path.join(BACKUP_DIR,path.basename(r.filename)))}catch{}await db.query('DELETE FROM backup_history WHERE id=?',[r.id])}}
async function latest(kind=null){const db=getPool(),where=kind?'WHERE backup_kind=?':'',params=kind?[kind]:[];const[[r]]=await db.query(`SELECT id,backup_kind,filename,file_size_bytes,created_at,downloaded_at FROM backup_history ${where} ORDER BY created_at DESC,id DESC LIMIT 1`,params);if(!r)return null;const filepath=path.join(BACKUP_DIR,path.basename(r.filename));return{id:Number(r.id),kind:r.backup_kind,filename:r.filename,fileSizeBytes:Number(r.file_size_bytes||0),createdAt:r.created_at,downloadedAt:r.downloaded_at,exists:fs.existsSync(filepath)}}
async function stateJson(){const last=await latest(),lastAuto=await latest('auto');return{last,lastAuto,unreadAutomatic:Boolean(lastAuto&&lastAuto.exists&&!lastAuto.downloadedAt),automaticEveryHours:24,format:'json'}}
async function getBackupFile(id){const[[r]]=await getPool().query('SELECT * FROM backup_history WHERE id=? LIMIT 1',[id]);if(!r)return null;const filename=path.basename(r.filename),filepath=path.join(BACKUP_DIR,filename);if(!fs.existsSync(filepath))return null;return{row:r,filename,filepath}}
async function markDownloaded(id){await getPool().query('UPDATE backup_history SET downloaded_at=NOW() WHERE id=?',[id])}
function validateBackup(p){if(!p||typeof p!=='object'||p.backup_format!=='appbit-json-backup'||![2,3].includes(Number(p.backup_version)))throw new Error('This is not a supported Appbit backup.');for(const k of ['apps','apk_versions','apk_media','apk_metadata','publish_queue'])if(!Array.isArray(p.data?.[k]))throw new Error('The backup is incomplete or damaged.');if(!Array.isArray(p.data.apk_categories))p.data.apk_categories=[];return p}
function normalizeDbValue(v,type=''){if(v==null)return v;const t=String(type).toLowerCase();if((t.includes('datetime')||t.includes('timestamp'))&&typeof v==='string'){const d=new Date(v);if(!Number.isNaN(d.getTime()))return d.toISOString().slice(0,19).replace('T',' ')}if(t.startsWith('date')&&typeof v==='string'){const m=v.match(/^(\d{4}-\d{2}-\d{2})/);if(m)return m[1]}return v}
async function insertRows(db,table,data){if(!data.length)return;const[colsRaw]=await db.query(`SHOW COLUMNS FROM \`${table}\``),meta=new Map(colsRaw.map(c=>[c.Field,c.Type]));for(const row of data){const cols=Object.keys(row).filter(k=>meta.has(k));if(!cols.length)continue;await db.query(`INSERT INTO \`${table}\` (${cols.map(c=>`\`${c}\``).join(',')}) VALUES (${cols.map(()=>'?').join(',')})`,cols.map(c=>normalizeDbValue(row[c],meta.get(c))))}}
async function restoreBackup(payload){validateBackup(payload);if(restoring)throw new Error('A restore is already in progress.');const safety=await createBackup('safety'),db=getPool(),conn=await db.getConnection();restoring=true;try{await conn.beginTransaction();await conn.query('SET FOREIGN_KEY_CHECKS=0');for(const t of ['publish_queue','apk_metadata','apk_media','apk_versions','app_work_claims','apps','apk_categories'])await conn.query(`DELETE FROM \`${t}\``);await insertRows(conn,'apps',payload.data.apps);await insertRows(conn,'apk_versions',payload.data.apk_versions);await insertRows(conn,'apk_media',payload.data.apk_media);await insertRows(conn,'apk_metadata',payload.data.apk_metadata);await insertRows(conn,'publish_queue',payload.data.publish_queue);if(payload.data.apk_categories.length)await insertRows(conn,'apk_categories',payload.data.apk_categories);else await conn.query(`INSERT INTO apk_categories (section,name,slug,parent_slug,sort_order,last_seen_at,active) SELECT COALESCE(source_section,'apps'),COALESCE(NULLIF(category,''),'Other'),COALESCE(NULLIF(category_slug,''),'other'),COALESCE(source_section,'apps'),999,NOW(),1 FROM apps GROUP BY COALESCE(source_section,'apps'),COALESCE(NULLIF(category,''),'Other'),COALESCE(NULLIF(category_slug,''),'other')`);await conn.query('SET FOREIGN_KEY_CHECKS=1');await conn.commit();return{restoredApps:payload.data.apps.length,restoredVersions:payload.data.apk_versions.length,safetyBackup:safety}}catch(err){try{await conn.query('SET FOREIGN_KEY_CHECKS=1')}catch{}try{await conn.rollback()}catch{}throw err}finally{conn.release();restoring=false}}
async function autoTick(){if(!state.dbReady||running||restoring)return;try{const lastAuto=await latest('auto'),age=lastAuto?.createdAt?Date.now()-new Date(lastAuto.createdAt).getTime():Infinity;if(!lastAuto||!Number.isFinite(age)||age>=AUTO_INTERVAL_MS){const r=await createBackup('auto');await activity.record(null,'backup_created',{details:{kind:'auto',filename:r.filename,fileSizeBytes:r.fileSizeBytes}});await notifications.notifyAdmins({type:'success',title:'Automatic backup completed',message:`${r.filename} is ready to download.`,dedupeKey:`auto-backup-${r.id}`});console.log(`[Appbit] Automatic JSON backup created: ${r.filename}`)}}catch(err){console.error('[Appbit] Automatic backup failed:',err?.message||err);try{await activity.record(null,'backup_failed',{details:{kind:'auto',error:String(err?.message||err).slice(0,500)}});await notifications.notifyAdmins({type:'error',title:'Automatic backup failed',message:String(err?.message||err).slice(0,500),dedupeKey:`auto-backup-failed-${new Date().toISOString().slice(0,10)}`})}catch{}}}
function startBackupWorker(){if(workerStarted)return;workerStarted=true;const first=setTimeout(autoTick,8000);if(first.unref)first.unref();const timer=setInterval(autoTick,CHECK_INTERVAL_MS);if(timer.unref)timer.unref()}
module.exports={createBackup,restoreBackup,validateBackup,state:stateJson,latest,getBackupFile,markDownloaded,startBackupWorker,BACKUP_DIR};
