const { getPool } = require('../db');
function notificationJson(row){if(!row)return null;return{id:Number(row.id),type:row.type||'info',title:row.title||'',message:row.message||'',appId:row.app_id==null?null:Number(row.app_id),appName:row.app_name||null,actorUserId:row.actor_user_id==null?null:Number(row.actor_user_id),actorName:row.actor_name||null,actorRole:row.actor_role||null,targetUserId:row.target_user_id==null?null:Number(row.target_user_id),isRead:Boolean(row.is_read),createdAt:row.created_at||null,readAt:row.read_at||null}}
async function notifyUser(userId,{actorUserId=null,type='info',title,message=null,appId=null,targetUserId=null,dedupeKey=null}={}){try{const [r]=await getPool().query(`INSERT INTO notifications (user_id,actor_user_id,type,title,message,app_id,target_user_id,dedupe_key) VALUES (?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE id=id`,[Number(userId),actorUserId?Number(actorUserId):null,String(type).slice(0,40),String(title||'Notification').slice(0,160),message?String(message).slice(0,700):null,appId?Number(appId):null,targetUserId?Number(targetUserId):null,dedupeKey?String(dedupeKey).slice(0,190):null]);return Number(r.insertId||0)}catch(err){console.error('[Appbit] Notification create failed:',err?.message||err);return null}}
async function activeAdminIds(){const [rows]=await getPool().query("SELECT id FROM users WHERE role='admin' AND is_active=1 ORDER BY id");return rows.map(r=>Number(r.id)).filter(Boolean)}
async function activeUserIds(){const [rows]=await getPool().query('SELECT id FROM users WHERE is_active=1 ORDER BY id');return rows.map(r=>Number(r.id)).filter(Boolean)}
async function notifyAdmins(payload={},opts={}){const out=[];for(const id of await activeAdminIds()){if(opts.exceptUserId&&Number(opts.exceptUserId)===id)continue;out.push(await notifyUser(id,payload))}return out.filter(Boolean)}
async function notifyAllActive(payload={},opts={}){const out=[];for(const id of await activeUserIds()){if(opts.exceptUserId&&Number(opts.exceptUserId)===id)continue;out.push(await notifyUser(id,payload))}return out.filter(Boolean)}
async function summary(userId){const [[r]]=await getPool().query('SELECT SUM(CASE WHEN is_read=0 THEN 1 ELSE 0 END) unread_count,MAX(id) latest_id,MAX(CASE WHEN is_read=0 THEN id ELSE NULL END) latest_unread_id FROM notifications WHERE user_id=?',[Number(userId)]);return{unreadCount:Number(r?.unread_count||0),latestId:Number(r?.latest_id||0),latestUnreadId:Number(r?.latest_unread_id||0)}}
async function list(userId,{limit=30,unreadOnly=false}={}){const safe=Math.max(1,Math.min(100,Math.floor(Number(limit||30)||30)));let where='n.user_id=?';if(unreadOnly)where+=' AND n.is_read=0';const [rows]=await getPool().query(`SELECT n.*,u.name actor_name,u.role actor_role,a.name app_name FROM notifications n LEFT JOIN users u ON u.id=n.actor_user_id LEFT JOIN apps a ON a.id=n.app_id WHERE ${where} ORDER BY n.created_at DESC,n.id DESC LIMIT ${safe}`,[Number(userId)]);return rows.map(notificationJson)}
async function getById(userId,id){const [[row]]=await getPool().query('SELECT n.*,u.name actor_name,u.role actor_role,a.name app_name FROM notifications n LEFT JOIN users u ON u.id=n.actor_user_id LEFT JOIN apps a ON a.id=n.app_id WHERE n.user_id=? AND n.id=? LIMIT 1',[Number(userId),Number(id)]);return notificationJson(row)}
async function markRead(userId,ids=[]){const clean=[...new Set((Array.isArray(ids)?ids:[ids]).map(Number).filter(Boolean))].slice(0,100);if(!clean.length)return 0;const [r]=await getPool().query(`UPDATE notifications SET is_read=1,read_at=COALESCE(read_at,NOW()) WHERE user_id=? AND id IN (${clean.map(()=>'?').join(',')})`,[Number(userId),...clean]);return Number(r.affectedRows||0)}
async function markAllRead(userId){const [r]=await getPool().query('UPDATE notifications SET is_read=1,read_at=COALESCE(read_at,NOW()) WHERE user_id=? AND is_read=0',[Number(userId)]);return Number(r.affectedRows||0)}
module.exports={notificationJson,notifyUser,notifyAdmins,notifyAllActive,summary,list,getById,markRead,markAllRead};
